routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

/**
 * Employee resource.
 * @author Juan Carlos Rivera Ortiz
 * @created 2021-07-30
 */
Route::put('employee/{employee}/status', [EmployeeController::class, 'status'])->name('employee.status');
Route::post('employee/datatable', [EmployeeController::class, 'datatable'])->name('employee.datatable');
Route::resource('employee', EmployeeController::class);

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Employee extends Model
{

    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     * @author Juan Carlos Rivera Ortiz
     * @created 2021-07-30
     * @var array
     */
    protected $fillable = [
        'name',
        'code',
        'last_name',
        'second_last_name',
        'email',
        'contract_type',
        'status'
    ];

    /**
     * The attributes that should be cast to native types.
     * @author Juan Carlos Rivera Ortiz
     * @created 2021-07-30
     * @var array
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use DataTables;
use Carbon\Carbon;
use App\Models\Employee;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\EmployeeRequest;

class EmployeeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('employees.index');
    }

     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function datatable()
    {
        $employees = Employee::get();
        return DataTables::of($employees)
            ->removeColumn('last_name')
            ->removeColumn('second_last_name')
            ->editColumn('name', function($employee) {
                return $employee->name . ' ' . $employee->last_name . ' ' . $employee->second_last_name;
            })
            ->addColumn('actions', function ($employee) {
                return view('employees.partials.buttons', ['employee' => $employee]);
            })
            ->make(true);   
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\EmployeeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        $validated = $request->validated();
        $validated['code'] = Str::random(10);
        Employee::create($validated);
        return redirect('/employee')->with('success', __('Saved Successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(employee $employee)
    {
        return view('employees.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        return view('employees.edit', compact('employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\EmployeeRequest  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, Employee $employee)
    {
        $validated = $request->validated();
        $employee->update($validated);
        return redirect('/employee')->with('success', __('Updated Successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return redirect('/employee')->with('success', __('Deleted Successfully'));
    }

    /**
     * Enable/Disable the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function status(Employee $employee)
    {
        if ($employee->status == 1) {
            $employee->status = 0;
            $employee->update();
            return redirect('/employee')->with('success', __('Status changed Successfully'));
        } else if ($employee->status == 0){
            $employee->status = 1;
            $employee->update();
            return redirect('/employee')->with('success', __('Status changed Successfully'));
        }
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span>{{ __('Add Employee') }}</span>
                </div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul class="mb-0">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('employee.store') }}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="name">{{ __('Name') }}</label>
                            <input type="text" value="{{ old('name') }}" class="form-control" name="name" id="name" placeholder="Enter name">
                        </div>
                        <div class="form-group">
                            <label for="last_name">{{ __('Last name') }}</label>
                            <input type="text"  value="{{ old('last_name') }}" class="form-control" name="last_name" id="last_name" placeholder="Enter last name">
                        </div>
                        <div class="form-group">
                            <label for="second_last_name">{{ __('Second last name') }}</label>
                            <input type="text" value="{{ old('second_last_name') }}" class="form-control" name="second_last_name" id="second_last_name" placeholder="Enter second last name">
                        </div>
                        <div class="form-group">
                            <label for="email">{{ __('Email') }}</label>
                            <input type="email" value="{{ old('email') }}"  class="form-control" name="email" id="email" placeholder="Enter email">
                        </div>
                        <div class="form-group">
                            <label for="contract_type">{{ __('Contract Type') }}</label>
                            <input type="text" value="{{ old('contract_type') }}" class="form-control" name="contract_type" id="contract_type" placeholder="Enter contract Type">
                        </div>
                        <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
                        <a href="{{ route('employee.index') }}" class="btn btn-danger">{{ __('Cancel') }}</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span>{{ __('Edit Employee') }}</span>
                </div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul class="mb-0">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('employee.update', ['employee'=> $employee->id]) }}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="name">{{ __('Name') }}</label>
                            <input type="text" value="{{ old('name', $employee->name) }}"  class="form-control" name="name" id="name" placeholder="Enter name">
                        </div>
                        <div class="form-group">
                            <label for="last_name">{{ __('Last name') }}</label>
                            <input type="text" value="{{ old('name', $employee->last_name) }}"  class="form-control" name="last_name" id="last_name" placeholder="Enter last name">
                        </div>
                        <div class="form-group">
                            <label for="second_last_name">{{ __('Second last name') }}</label>
                            <input type="text" value="{{ old('name', $employee->second_last_name) }}"  class="form-control" name="second_last_name" id="second_last_name" placeholder="Enter second last name">
                        </div>
                        <div class="form-group">
                            <label for="email">{{ __('Email') }}</label>
                            <input type="email" value="{{ old('name', $employee->email) }}"  class="form-control" name="email" id="email" placeholder="Enter email">
                        </div>
                        <div class="form-group">
                            <label for="contract_type">{{ __('Contract Type') }}</label>
                            <input type="text" value="{{ old('name', $employee->contract_type) }}"  class="form-control" name="contract_type" id="contract_type" placeholder="Enter contract Type">
                        </div>
                        <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
                        <a href="{{ route('employee.index') }}" class="btn btn-danger">{{ __('Cancel') }}</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span>{{ __('Employees') }}</span>
                    <a href="{{ route('employee.create') }}" class="btn btn-success float-right">{{ __('Add employee') }}</a>
                </div>
                <div class="card-body">
                    @if (session()->has('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif
                    <table id="data_table">
                        <thead>
                            <tr>
                                <th>{{ __('ID') }}</th>
                                <th>{{ __('Code') }}</th>
                                <th>{{ __('Name') }}</th>
                                <th>{{ __('Email') }}</th>
                                <th>{{ __('Contract_type') }}</th>
                                <th>{{ __('Status') }}</th>
                                <th>{{ __('Updated at')}}</th>
                                <th>{{ __('Created at')}}</th>
                                <th>{{ __('Actions')}}</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('css')
    <link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/responsive/2.2.6/css/responsive.bootstrap.min.css" rel="stylesheet" type="text/css" />
@endsection

@section('js')
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js" defer></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js" defer></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.jsdelivr.net/npm/luxon@1.25.0/build/global/luxon.min.js"></script>
    <script>
        var DateTime = luxon.DateTime;
        $(document).ready(function () {
            $('#data_table').DataTable({
                serverSide: true,
                ajax: {
                    headers: {
                        'X-CSRF-TOKEN': "{{csrf_token()}}"
                    },
                    url:  "{{ route('employee.datatable') }}",
                    method: 'POST'
                },
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'code', name: 'code'},
                    {data: 'name', name: 'name'},
                    {data: 'email', name: 'email'},
                    {data: 'contract_type', name: 'contract_type'},
                    {
                        mData: "status",
                        mName: "status",
                        mRender: function (data, type, row) {
                            if (data == 1) {
                                return 'Active';
                            } else {
                                return 'Innactive';
                            }
                        }
                    },
                    {
                        mData: "updated_at",
                        mName: "updated_at",
                        mRender: function (data, type, row) {
                            return DateTime.fromISO(data, {zone: 'America/Monterrey'}).setLocale('es-CO').toFormat("DDD 'a las' t");
                        }
                    },
                    {
                        mData: "created_at",
                        mName: "created_at",
                        mRender: function (data, type, row) {
                            return DateTime.fromISO(data, {zone: 'America/Monterrey'}).setLocale('es-CO').toFormat("DDD 'a las' t");
                        }
                    },
                    {data: 'actions', name: 'actions', orderable: false, searchable: false},
                ]
            });
        });
    </script>
@endsection

resources/views/employees/partials/buttons.blade.php
<div class="btn-group" role="group">
    <a href="{{ route('employee.edit', ['employee'=> $employee]) }}" class="btn btn-primary">{{ __('Edit') }}</a>
    <a href="{{ route('employee.show', ['employee'=> $employee]) }}" class="btn btn-info">{{ __('Show') }}</a>
    <form class="btn-group" action="{{ route('employee.status', ['employee'=> $employee]) }}" method="post">
      @csrf
      @method('PUT')
      <button type="submit" class="{{ $employee->status == 1 ? 'btn btn-warning' : 'btn btn-success' }}">{{ $employee->status == 1 ? __('Deactivate') : __('Activate') }}</button>
    </form>
    <form class="btn-group" action="{{ route('employee.destroy', ['employee'=> $employee]) }}" method="post">
        @csrf
        @method('DELETE')
        <button type="submit" class="btn btn-danger">{{ __('Delete') }}</button>
    </form>
</div>

resources/views/employees/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span>{{ __('Employee ' . $employee->id ) }}</span>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <h6 class="font-weight-bold" for="id">{{ __('ID') }}: <span class="font-weight-normal">{{ $employee->id }}</span></h6>
                    </div>
                    <div class="form-group">
                        <h6 class="font-weight-bold" for="code">{{ __('Code') }}: <span class="font-weight-normal">{{ $employee->code }}</span></h6>
                    </div>
                    <div class="form-group">
                        <h6 class="font-weight-bold" for="name">{{ __('Name') }}: <span class="font-weight-normal">{{ $employee->name }}</span></h6>
                    </div>
                    <div class="form-group">
                        <h6 class="font-weight-bold" for="last_name">{{ __('Last name') }}: <span class="font-weight-normal">{{ $employee->last_name }}</span></h6>
                    </div>
                    <div class="form-group">
                        <h6 class="font-weight-bold" for="second_last_name">{{ __('Second last name') }}: <span class="font-weight-normal">{{ $employee->second_last_name }}</span></h6>
                    </div>
                    <div class="form-group">
                        <h6 class="font-weight-bold" for="email">{{ __('Email') }}: <span class="font-weight-normal">{{ $employee->email }}</span></h6>
                    </div>
                    <div class="form-group">
                        <h6 class="font-weight-bold" for="contract_type">{{ __('Contract Type') }}: <span class="font-weight-normal">{{ $employee->contract_type }}</span></h6>
                    </div>
                    <div class="form-group">
                        <h6 class="font-weight-bold" for="status">{{ __('Status') }}: <span class="font-weight-normal">{{ $employee->status == 1 ? 'Active' : 'Innactive'; }}</span></h6>
                    </div>
                    <a href="{{ route('employee.index') }}" class="btn btn-primary">{{ __('Go back') }}</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    @yield('js')

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('css')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>